language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.7
- 2.4.4
- 2.5.1
script:
- bundle exec rake default
- gem build sensu-plugins-hangouts-chat.gemspec
- gem install sensu-plugins-hangouts-chat-*.gem
